version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: kyrgyz-medical-card-db

    environment:
      POSTGRES_DB: kyrgyz_medical_card
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped


  backend:
    build:

      context: .
      dockerfile: Dockerfile
    container_name: kyrgyz-medical-card-backend

    depends_on:
      - db

    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/kyrgyz_medical_card
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "8080:8080"
    restart: unless-stopped


  frontend:
    build:
      context: ./code-frontend/Хакатон
      dockerfile: Dockerfile
    container_name: kyrgyz-medical-card-frontend
    ports:
      - "3000:3000"

    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
