services:
  app:
    build: .
    image: kyrgyz-medical-card-application:latest
    ports:
      - 8080:8080
    depends_on:
      - db
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kyrgyz_medical_card
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - MINIO_URL=http://172.17.0.3:9000
      - MINIO_ACCESS-KEY=minioadmin
      - MINIO_SECRET-KEY=minioadmin
      - MINIO_BUCKET_NAME_DIAGNOSIS=DIAGNOSIS
      - MINIO_BUCKET_NAME_NEWS=NEWS
    networks:
      custom_net:
        ipv4_address: 172.30.0.10

  db:
    image: postgres
    environment:
      - POSTGRES_DB=kyrgyz_medical_card
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      custom_net:
        ipv4_address: 172.30.0.2

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=admin
    volumes:
      - minio-data:/data
    command:
      - server
      - --console-address
      - ":9001"
      - /data
    networks:
      custom_net:
        ipv4_address: 172.30.0.3

volumes:
  minio-data:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/18