@token = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlcm5hbWUiOiIxMjMiLCJzdWIiOiIxMjMiLCJpYXQiOjE3NjU3MDQ1ODUsImV4cCI6MTc2NTcwODE4NX0.XOiZ42Ir5uHn3a50n_arkWbSzx8TC2DqwVd9NnFph9I

### Запрос 2: Вход пользователя

# Этот запрос использует формат x-www-form-urlencoded
POST 192.168.102.222:8080/api/users/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "1",
  "inn": "123",
  "fio": "123",
  "gender": "Male",
  "birthday": "2025-12-25",
  "en": "+996123123",
  "enName": "Отец",
  "blood": "I",
  "rh": "+"
}

### Запрос 8:

POST 192.168.102.222:8080/api/medicine-insurance/create-medicine-insurance
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "insuranceName": "ОМС",
  "description": "{\"d1\": \"Консультации\", \"d2\": \"Диагностика\", \"d3\": \"Стационар\", \"d4\": \"Профилактика\"}",
  "price": 15000.00
}

### Запрос 9:

POST 192.168.102.222:8080/api/medicine-insurance/create-medicine-insurance
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "insuranceName": "ОМС",
  "description": "{\"d1\": \"Консультации\", \"d2\": \"Диагностика\", \"d3\": \"Стационар\", \"d4\": \"Профилактика\", \"d5\": \"Покрытие лекарств\", \"d6\": \"Экстриная помощь\"}",
  "price": 15000.00
}

### Запрос 2: Вход пользователя (POST /api/auth/login)

# Этот запрос использует формат x-www-form-urlencoded
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "inn": "12345678901236",
  "password": "Almanbet@ssw0rd123"
}


###

GET http://localhost:8080/api/auth/get-current
Authorization: Bearer {{token}}