ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_phone VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS blood_group VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rh_factor VARCHAR;
